export const prompts = [
  "A flying elephant",
  "Your favorite food",
  "A superhero squirrel",
  "A robot playing guitar",
  "A dragon drinking tea",
  "A house on a cloud",
  "A cat reading a book",
  "A dancing cactus",
  "A tree with eyes",
  "The moon singing a song",
  "A surfing penguin",
  "A donut in space",
  "A detective flamingo",
  "An octopus juggling",
  "A wizard frog",
  "A car that can fly",
  "A musical spiderweb",
  "A shy monster under the bed",
  "A ghost eating toast",
  "A sunflower with a face",
];
